version: '3'
services:
  ocaml_app:
    image: ocaml/opam:alpine-ocaml-4.12
    container_name: ocaml_container
    volumes:
      - .:/app
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        opam install yojson
        opam install ocamlfind
        sh
    tty: true
    stdin_open: true